apiVersion: v1
kind: Pod
metadata: 
  name: first-nginx
  labels:
    env: prod
    app: nginx
    schtroumpf: grognon
spec:
  containers:
    - name: nginx-container
      image: nginx:stable-trixie
      env:
        - name: NODE_VERSION
          value: 24
        - name: NGINX_VERSION
          value: latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 0.5
          memory: "50Mi"
        limits:
          cpu: 1
          memory: "200Mi"