# =============================================================================
# Namespace de l'app de test
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    name: demo
